spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers:
            localhost:9092
          auto-create-topics: true
          configuration:
            security.protocol: PLAINTEXT
      bindings:
        consumer-in-0:
          destination: consumer.input
          group: input
        default:
          contentType: application/json
      default-binder: kafka
    function:
      definition: consumer